### ISSUE TITLE
Maven support

### ISSUE THREAD

**Issue by ghost** [RalleYTN/SimpleJSON#1]
Can I find the library in a maven repository?
Or can we get an jar file containing all the files?

**Comment by RalleYTN** [comment]
Since I never worked with Maven, I never really planned on adding Maven support. But I can do some research and try to add it.

There already is a ZIP containing pre-compiled stuff in [releases](https://github.com/RalleYTN/SimpleJSON/releases).

**Comment by ghost** [comment]
More default to add the jar to Maven can be found at:
https://maven.apache.org/guides/mini/guide-central-repository-upload.html

**Comment by RalleYTN** [comment]
Maven is now supported.
