### ISSUE TITLE
How come the JSONArray extends ArrayList<Object> instead of ArrayList<JSONObject>

### ISSUE THREAD

**Issue by JTKlemmensen** [RalleYTN/SimpleJSON#2]
I dont expect an answer but i do think it should be changed.

**Comment by RalleYTN** [comment]
because an array can hold elements of any type. an array can also hold different types at the same time.

here an example of a valid JSON array that has no JSON objects:
```json
[
    "hello",
    "world"
]
```

**Comment by JTKlemmensen** [comment]
Oh ok i did not know that. Thank you for the answer.
