### ISSUE TITLE
No Exceptions Occur with Invalid JSON String

### ISSUE THREAD

**Issue by jredfox** [RalleYTN/SimpleJSON#5]
Original issue found here and still persists in current library:
https://github.com/fangyidong/json-simple/issues/16

Test code no exceptions occur when it should occur:
https://pastebin.com/nq0CfHjX

Test 2 this is an invalid json string due to a dupe key when parsing. It''s fine if you want to replace a key using JSONObject.pu() in memory but, when parsing it from a file/invalid sting if they key already exists in that file/string then it is no longer acceptable
```
JSONParser parser = new JSONParser();
System.out.println("Done:" + parser.parse("{\"key\":1 \"key\":2}"));
```

**Comment by RalleYTN** [comment]
I actually think it is better to be liberal with input and conservative with the output. Is there any case in which it is necessary to actually check for this? I can't think of any practical cases.

**Comment by jredfox** [comment]
no read the code there are no commas and it was still parsing

**Comment by RalleYTN** [comment]
I will try to add a new method in the JSONParser which will validate JSON according to format definition.

**Comment by RalleYTN** [comment]
Fixed with newest commit.
By adding `true` as a second parameter to `parse` you will enable strict mode which will validate the existence of colons and commas. Adiitionally `JSONObject` and `JSONArray` now have new constructors that allow parsing with strict mode.

This code will now throw a JSONParseException:
```java
JSONParser parser = new JSONParser();
System.out.println("Done:" + parser.parse("{\"key\":1 \"key\":2}", true));
```
