### ISSUE TITLE
Pretty Print String Limitations

### ISSUE THREAD

**Issue by jredfox** [RalleYTN/SimpleJSON#6]
Pretty print in JSONFormatter doesn't allow for printing large json objects to a file only the indexed amount of chars which in unicode form most common json type is around 500 million chars. Sounds like alot but, actually isn't for a decent size json file.

Yes you can still support string/reader but, there should be a method inside where it only accepts Writer and will properly write the whole json object/array to the file the first time

**Comment by RalleYTN** [comment]
Will add the methods
- JSONFormatter#format(JSONObject,Writer)
- JSONFormatter#format(JSONArray,Writer)
in the next release

**Comment by jredfox** [comment]
this is still next fixed can you please add this feature?

**Comment by RalleYTN** [comment]
> this is still next fixed can you please add this feature?

Issue fixed with newest commit.
