### ISSUE TITLE
Pretty Print Not Proper Printing Algorithm

### ISSUE THREAD

**Issue by jredfox** [RalleYTN/SimpleJSON#7]
Pretty print doesn't look right when outputted compared to test against gson https://github.com/google/gson and https://jsoneditoronline.org/

Also on windows you fail to provide the proper line mechanics making me use non native windows notepad to edit the file. \r\n is the proper format or get it dynamically from the system.

**Comment by RalleYTN** [comment]
I'll look into it but could you give me more info on why the output looks wrong?
Do you have an example JSON string in which these errors occur?

for the line break on windows you should use the following method:
```java
JSONFormatter formatter = new JSONFormatter();
formatter.setUseCRLF(true); // flag that makes the formatter use \r\n instead of \n
```

**Comment by jredfox** [comment]
just do what the steps to reproduce are then compare the same string with json editor online after formatting it to theirs it looks way different.

**Comment by RalleYTN** [comment]
Again the JSONFormatter class has methods that allow for customizing the pretty print output. In case of line break mechanics you can set it to use windows line breaks with the setUseCRLF method inside the JSONFormatter. you can also use methods like setIndent to determine the indent and setUseTabs to set wether the indent should use tabs or spaces.

I will close this issue as it really isnt an issue.
